name: challenge

on: push

jobs:
  job1:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date
  job2:
    name: Second job
    runs-on: windows-latest
    steps:
      - name: print date
        run: date
  job3:
    name: Third job
    runs-on: macos-latest
    steps:
      - name: print date
        run: date
  job4:
    name: Forth job
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: date